### ISSUE TITLE
How can I get a client key for send data to kancolle-db.net?

### ISSUE THREAD

**Issue by tsanie** [about518/kanColleDbPost#3]
Hello!

I use kancolle-db.net a lot, but never contribute it.
So I'm very ashamed about it, and want to send my data to it.

I use the ElectronicObserver (https://github.com/andanteyk/ElectronicObserver), and I don't know how to get a client key "agent" with it. (I've registered in kancolle-db.net and got an oauth key)

**Comment by about518** [comment]
Client key "Agent" has issued manually.
If you want to use "ElectronicObserver" client, please use this key
```
L57Mi4hJeCYinbbBSH5K
```
It key has been already available.

**Comment by tsanie** [comment]
Thank you for answer!

But I've got an error after upload the data.
```<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/kancolle-db/api/2/index.php</b> on line <b>13</b><br />```

It happens at ```[2015/5/27 8:38:24 UTC+8]```

I post the data for ```[token, agent, url, requestbody, responsebody]``` used NameValueCollection with WebClient

**Comment by tsanie** [comment]
Oh, it success!
I just found it occurs error in 'api_get_member/kdock', but success in 'api_port/port'

**Comment by about518** [comment]
> But I've got an error after upload the data.
> <br /> <b>Warning</b>: Invalid argument supplied for foreach() in <b>/var/www/kancolle-db/api/2/index.php</b> on line <b>13</b><br />

It was API side bug. I fixed it. Thanks!
